### ISSUE TITLE
The error was: AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by ernesto-miranda** [dgraum/datapower-ansible#1]
Hi @dgraum ,

Thanks for the hard work you've done here!!

When I try to execute any of the examples I run into the following error:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'startswith'
fatal: [localhost]: FAILED! => {"failed": true, "stdout": ""}
```

The whole execution would be like:

```
emiranda@ubuntu:~/ansible/datapower/datapower-ansible$ ansible-playbook examples/domain_config/save.yml -e "domain_name=default"

PLAY [Test DataPower domain module (save)] *************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Include connection data] *************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'startswith'
fatal: [localhost]: FAILED! => {"failed": true, "stdout": ""}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   

emiranda@ubuntu:~/ansible/datapower/datapower-ansible$ 
```

If I use "-vvv" to get a verbose output:

```
emiranda@ubuntu:~/ansible/datapower/datapower-ansible$ ansible-playbook examples/domain/create.yml -e "domain_name=test1" -vvv
Using /home/emiranda/ansible/datapower/datapower-ansible/ansible.cfg as config file
1 plays in examples/domain/create.yml

PLAY [Test DataPower domain module (create)] ***********************************

TASK [setup] *******************************************************************
ESTABLISH LOCAL CONNECTION FOR USER: emiranda
localhost EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1530908403.96-154546995692577 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1530908403.96-154546995692577 )" )
localhost PUT /tmp/tmp5uQp5s TO /home/emiranda/.ansible/tmp/ansible-tmp-1530908403.96-154546995692577/setup
localhost EXEC LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/emiranda/.ansible/tmp/ansible-tmp-1530908403.96-154546995692577/setup; rm -rf "/home/emiranda/.ansible/tmp/ansible-tmp-1530908403.96-154546995692577/" > /dev/null 2>&1
ok: [localhost]

TASK [Include connection data] *************************************************
task path: /home/emiranda/ansible/datapower/datapower-ansible/examples/domain/create.yml:9
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/executor/process/worker.py", line 114, in run
    self._shared_loader_obj,
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 119, in run
    res = self._execute()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 401, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/include_vars.py", line 41, in run
    source = self._loader.path_dwim_relative(self._loader.get_basedir(), 'vars', source)
  File "/usr/lib/python2.7/dist-packages/ansible/parsing/dataloader.py", line 230, in path_dwim_relative
    if source.startswith('~') or source.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'

fatal: [localhost]: FAILED! => {"failed": true, "stdout": ""}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   

emiranda@ubuntu:~/ansible/datapower/datapower-ansible$ 
```

More details:

- No matter what playbook I run, I always get the same error.
- So far I am just trying to run the examples, just getting familiar with the module.
- The IDG seems to be working properly. I am able to access to both GUI and CLI. The docker command I am using is:
 ```sudo docker run -it -e DATAPOWER_ACCEPT_LICENSE=true -e DATAPOWER_INTERACTIVE=true -e DATAPOWER_WORKER_THREADS=4 -p 9090:9090 -p 5554:5554 ibmcom/datapower```
- I successfully enabled REST MGMT and GUI by using the sequence of commands you stated in the README file

**Comment by ernesto-miranda** [comment]
Additional info, I am using:
-  Ubuntu 16.04
- Ansible 2.0.0.2
- Docker version 18.03.1-ce

**Comment by dgraum** [comment]
Hello Ernesto;

This is a known issue of your version of Ansible. [https://github.com/ansible/ansible-modules-core/issues/4449](https://github.com/ansible/ansible-modules-core/issues/4449)

Please, update and try again. [https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#latest-releases-via-apt-ubuntu](https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#latest-releases-via-apt-ubuntu)

Thank you!

**Comment by ernesto-miranda** [comment]
Thanks @dgraum 

It perfectly works after updating Ansible!!
